name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Fix dubious ownership error
      run: git config --global --add safe.directory '*'
    - name: Build Zelda3 switch
      run: |
        cd platform/switch
        make
        cd -
        mkdir uploads
        ls -al platform/switch
        cp platform/switch/{zelda3.nro,zelda3.ini} uploads
        #cp platform/switch/zelda3.ini uploads
        
    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: Zelda3-switch
        path: uploads/
