name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-sm:
    strategy:
      fail-fast: false
      matrix:
        name: [windows] # [linux, switch, macos] 
        include:
          #- name: linux
          #  os: ubuntu-latest
          #- name: switch
          #  os: ubuntu-latest
          #  container: devkitpro/devkita64:latest
          #  toolchain: /opt/devkitpro/cmake/Switch.cmake
          - os: windows-latest
            name: windows
            toolchain: D:/a/zelda3/zelda3/vcpkg/scripts/buildsystems/vcpkg.cmake
          #- os: macos-latest
          #  name: macos

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        repository: LaserEyess/sm
        ref: cmake
        submodules: recursive
    - name: Fix dubious ownership error
      run: |
        git config --global --add safe.directory '*'
        sed -i 's/3.22/3.18/g' CMakeLists.txt
      if: ${{ matrix.name == 'switch' }}
    - name: Install Deps linux
      run: sudo apt install libsdl2-dev
      if: ${{ matrix.name == 'linux' }}
    - name: Install Deps macos
      run: brew install SDL2
      if: ${{ matrix.name == 'macos' }}
    - name: Install Deps windows
      run: |
        git clone https://github.com/microsoft/vcpkg
        git clone https://github.com/aminosbh/sdl2-cmake-modules cmake/sdl2
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install sdl2:x64-windows
        #get-content CMakeLists.txt | %{$_ -replace "REQUIRED COMPONENTS SDL2-static","CONFIG REQUIRED"}
      if: ${{ matrix.name == 'windows' }}    
    - name: Build ${{ matrix.name }} sm
      run: |
        cmake -S . -Bbuild -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }} -DCMAKE_MODULE_PATH="D:/a/zelda3/zelda3/cmake/sdl2" -DCMAKE_PREFIX_PATH="D:/a/zelda3/zelda3/vcpkg/installed/x64-windows/share/sdl2"
        cmake --build build
        #ls -al build
        #mkdir uploads
        #cp build/sm* uploads
        #cp sm.ini uploads
        #ls -al uploads
    #- name: Upload sm
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: sm-${{ matrix.name }}
    #    path: uploads/
