name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:

        
  build-windows:
    runs-on: windows-latest
    env:
      sdl: 2.28.1
    steps:
    - uses: actions/checkout@v3
      with:
        repository: LaserEyess/sm
        ref: cmake
        submodules: recursive
    - name: Install deps
      run: |
        curl.exe --silent -o SDL2.zip https://www.libsdl.org/release/SDL2-devel-${{ env.sdl }}-VC.zip
        tar -xf SDL2.zip
    - name: Build sm
      run: |
        cmake -Bbuild -DCMAKE_PREFIX_PATH=%CD%/SDL2-${{ env.sdl }}
        cmake --build build
        mkdir uploads
        copy build\Debug\sm.exe uploads
        copy sm.ini uploads
        copy SDL2-${{ matrix.sdl }}/lib/x64/SDL2.dll uploads
    - name: Upload sm
      uses: actions/upload-artifact@v3
      with:
        name: sm-windows
        path: uploads/
