name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v3
    - name: Fix dubious ownership error
      run: git config --global --add safe.directory '*'
    - name: Build Zelda3 switch
      run: |
        cd platform/switch
        make
        ls -al
        pwd
        cd -
        mkdir uploads
        mkdir test
        ls -al platform/switch
        cp platform/switch/zelda3.nro uploads
        cp platform/switch/zelda3.ini uploads
        cp /__w/zelda3/zelda3/platform/switch/zelda3.{nro,ini} test || true
        
    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: Zelda3
        path: uploads/
