name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: switchbrew/switch-examples
        ref: master
    - name: Fix dubious ownership error
      run: git config --global --add safe.directory '*'
    - name: Build Switch Example #1
      run: |
        cd fs/sdmc
        sed -i 's/("")/(".")/g' source/main.c
        make
        cd -
        mkdir uploads
        ls -al fs/sdmc
        cp -r fs/sdmc uploads
    - name: Build Switch Example #2
      run: |
        cd fs/romfs
        make
        cd -
        mkdir uploads
        ls -al fs/romfs
        cp -r fs/romfs uploads
        
    - name: Upload Examples
      uses: actions/upload-artifact@v3
      with:
        name: Examples
        path: uploads/
