name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-sm:
    strategy:
      fail-fast: false       
      matrix:
        name: [switch] # [windows, linux, switch, macos] 
        include:
          - name: linux
            os: ubuntu-latest
          - name: switch
            os: ubuntu-latest
            container: devkitpro/devkita64:latest
            toolchain: -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake
          - os: windows-latest
            name: windows
            sdl: 2.28.1
            toolchain: -DCMAKE_PREFIX_PATH=D:/a/zelda3/zelda3/SDL2-
          - os: macos-latest
            name: macos

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        repository: LaserEyess/sm_rewrite
        ref: cmake
        submodules: recursive
    - name: Fix dubious ownership error
      run: |
        git config --global --add safe.directory '*'
        sed -i 's/3.22/3.18/g' CMakeLists.txt
        pacman -S cmake
      if: ${{ matrix.name == 'switch' }}
    - name: Install Deps linux
      run: sudo apt install libsdl2-dev
      if: ${{ matrix.name == 'linux' }}
    - name: Install Deps macos
      run: brew install SDL2
      if: ${{ matrix.name == 'macos' }}
    - name: Install Deps windows
      run: |
        curl.exe --silent -o SDL2.zip https://www.libsdl.org/release/SDL2-devel-${{ matrix.sdl }}-VC.zip
        tar -xf SDL2.zip
      if: ${{ matrix.name == 'windows' }}    
    - name: Build ${{ matrix.name }} sm
      run: |
        cmake -Bbuild ${{ matrix.toolchain }}${{ matrix.sdl }}
        cmake --build build
    - name: Prepare Uploads
      run: |
        mkdir uploads
        cp build/sm* uploads
        cp sm.ini uploads
      if: ${{ matrix.name != 'windows' }}
    - name: Prepare Uploads
      run: |
        mkdir uploads
        copy build\Debug\sm.exe uploads
        copy sm.ini uploads
        copy SDL2-${{ matrix.sdl }}/lib/x64/SDL2.dll uploads
      if: ${{ matrix.name == 'windows' }}
    - name: Upload sm
      uses: actions/upload-artifact@v3
      with:
        name: sm-${{ matrix.name }}
        path: uploads/
