name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-switch:
    strategy:
      fail-fast: false
      matrix:
        rom: [smw,smb1,smbll]
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: snesrev/smw
        ref: main
        submodules: recursive
    - name: Fix dubious ownership error
      run: git config --global --add safe.directory '*'
    - name: Build ${{ matrix.rom }} switch
      run: |
        SWITCH_MAKE=src/platform/switch
        mkdir -p uploads/${{ matrix.rom }}
        sed -i 's/smw.sfc/${{ matrix.rom }}.sfc/g' src/main.c
        cd $SWITCH_MAKE
        sed "s/smw/${{ matrix.rom }}/g"  > Makefile.${{ matrix.rom }}
        make -f Makefile.${{ matrix.rom }}
        cd -
        ls -al src/platform/switch
        cp src/platform/switch/${{ matrix.rom }}.nro uploads/${{ matrix.rom }}
        cp src/platform/switch/smw.ini uploads/${{ matrix.rom }}
        
    - name: Upload ${{ matrix.rom }}-switch
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.rom }}-switch
        path: uploads/${{ matrix.rom }}
