name: Build

on:
  push:
    branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-switch:
    strategy:
      fail-fast: false
      matrix:
        name: [linux, switch, macos] #-latest] #,windows-latest,macos-latest]
        include:
          - name: linux
            os: ubuntu-latest
          - name: switch
            os: ubuntu-latest
            container: devkitpro/devkita64:latest
            toolchain: /opt/devkitpro/cmake/Switch.cmake
          #- os: windows-latest
          #  name: windows
          - os: macos-latest
            name: macos

    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        repository: LaserEyess/sm
        ref: cmake
        submodules: recursive
    - name: Fix dubious ownership error
      run: |
        git config --global --add safe.directory '*'
        sed -i 's/3.22/3.18/g' CMakeLists.txt
      if: ${{ matrix.name == 'switch' }}
    - name: Install Deps ${{ matrix.name }}
      run: sudo apt install libsdl2-dev
      if: ${{ matrix.name == 'linux' }}
    - name: Install Deps ${{ matrix.name }}
      run: .\vcpkg\vcpkg install sdl2:x64-windows
      if: ${{ matrix.name == 'windows' }}    
    - name: Build ${{ matrix.name }} sm
      run: |
        cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }}
        cmake --build build
        ls -al build
        mkdir uploads
        cp build/sm* uploads
        cp sm.ini uploads
        ls -al uploads
        
    #- name: Upload sm
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: sm-${{ matrix.name }}
    #    path: uploads/
