name: Build

on:
  push:
    #branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-unix:
    name: Zelda3
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies for Linux
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev

    - name: Build
      run: make -j$(nproc) zelda3

    - name: Package AppImage
      run: |
        export LINUXDEPLOY="linuxdeploy-x86_64.AppImage --appimage-extract-and-run"
        export CONDA_PACKAGES="pyyaml;pillow"
        curl -sSflO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        curl -sSflO https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-conda/master/linuxdeploy-plugin-conda.sh
        chmod +x linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-plugin-conda.sh
        "$LINUXDEPLOY" --appdir=AppDir
        cp zelda3 AppDir/usr/bin/
        cp platform/appimage/{AppRun,zelda3.desktop,zelda3.png} AppDir
        chmod +x AppDir/AppRun
        chmod +x AppDir/usr/bin/zelda3
        mkdir -p AppDir/usr/assets
        cp -r {tables,other} AppDir/usr/assets/
        "$LINUXDEPLOY" --appdir=AppDir --plugin conda --output appimage
        mkdir uploads
        mv *.AppImage uploads

    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: Zelda3
        path: uploads/
        
