name: Build

on:
  push:
    #branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-unix:
    name: Zelda3
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies for Linux
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libnotify-bin zenity

    - name: Build
      run: make -j$(nproc) zelda3

    - name: Package AppImage
      run: chmod +x platform/appimage/appimage.sh && platform/appimage/appimage.sh

    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: Zelda3
        path: uploads/
        
