name: Build

on:
  push:
    #branches:
    #- master
  pull_request:
  workflow_dispatch:

jobs:
  build-unix:
    name: on macos-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies for Mac
      if: ${{ matrix.name == 'Mac' }}
      run: |
        brew install sdl2 coreutils
    - name: Build
      run: make -j$(nproc) zelda3
    - name: Package Mac bundle
      run: chmod +x platform/macosx/macos.sh && platform/macosx/macos.sh

    - name: Upload Bundle
      uses: actions/upload-artifact@v3
      with:
        name: Zelda3
        path: uploads/
